[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "environments"
version = "0.1.0"
description = "Standalone and work-in-progress environment definitions for `railroad`."
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "railroad",  # Using the local 'railroad' package
    "pyrobosim>=4.3.3",
    "imageio[ffmpeg]>=2.37.2",
]

[project.entry-points."railroad.benchmarks"]
environments = "environments.benchmarks"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
