[project]
name = "mrppddl-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "gregory.j.stein@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
	     "mrppddl"
]

[tool.uv]
package = true